version: 0
hosts:
  visiongpy: &vision01
    ip: "visiongpu50"
    username: "{env.JYNS_USERNAME}"
    password: "{env.JYNS_PASSWORD}"
    launch_dir: "{env.JYNS_DIR}/dreamerv2/{now:%Y-%m-%d}/{now:%H%M%S.%f}"
  # supercloud
  gaia: &login_node !host
    ip: "{env.JYNS_SLURM_HOST}"
    username: "{env.JYNS_USERNAME}"
    pem: "{env.JYNS_SLURM_PEM}"
mounts: # mount configurations Available keys: NOW, UUID,
  - !mounts.SSHCode &supercloud_code_mount
    local_path: .
    # host_path: $JYNMNT/latent-planning/latent-planning
    local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-dmc_gen.tar
    host_path: "{env.JYNS_SLURM_DIR}/dreamerv2/{now:%Y-%m-%d}/{now:%H%M%S.%f}-dmc_gen"
    remote_tar: "{env.JYNS_SLURM_DIR}/dreamerv2/{now:%Y-%m-%d}/{now:%H%M%S.%f}-dmc_gen.tar"
    pypath: true
    excludes: >-
      --exclude='data' --exclude='samples' --exclude='images' --exclude='videos'
      --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
      --exclude='*__pycache__' --exclude='*.git' --exclude='*.png' --exclude='*.gif'
      --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
      --exclude='*.log*' --exclude='custom_vendor'
    compress: true
  - !mounts.SSHCode &csail_code_mount
    local_path: .
    # host_path: $JYNMNT/latent-planning/latent-planning
    local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-dmc_gen.tar
    host_path: "{env.JYNS_DIR}/dreamerv2/{now:%Y-%m-%d}/{now:%H%M%S.%f}-dmc_gen"
    remote_tar: "{env.JYNS_DIR}/dreamerv2/{now:%Y-%m-%d}/{now:%H%M%S.%f}-dmc_gen.tar"
    pypath: true
    excludes: >-
      --exclude='data' --exclude='samples' --exclude='images' --exclude='videos'
      --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
      --exclude='*__pycache__' --exclude='*.git' --exclude='*.png' --exclude='*.gif'
      --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
      --exclude='*.log*' --exclude='custom_vendor'
    compress: true
runners:
  - !runners.Simple &ssh_runner
    setup: |
      source $HOME/.bashrc
      conda activate dmcgen
    envs: >-
      LANG=utf-8
      LC_CTYPE=en_US.UTF-8
    pypath: "{mounts[0].host_path}"
    work_dir: "{mounts[0].host_path}"
  - !runners.Slurm &supercloud-slurm
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US
      HTTP_PROXY=http://login-2:8082
      LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/gridsan/geyang/.mujoco/mujoco200/bin
    startup: >-
      source ~/.bashrc;
      module load cuda/11.0;
      module load anaconda/2020b;
      source activate dmcgen;
      cp -r /state/partition1/user/$USER/mujoco-py /home/gridsan/$USER/;
    pypath: "{mounts[0].host_path}"
    work_dir: "{mounts[0].host_path}"
    partition: normal # not clear what the partition is like
    exclude: d-10-4-1
    # time_limit: "0:0:20"
    n_cpu: 8
    n_gpu: volta:1

modes:
  visiongpu: &vision
    host: !host
      <<: *vision01
    mounts:
      - *csail_code_mount
    runner: *ssh_runner
    launch:
      type: ssh
      <<: *vision01
  supercloud: &supercloud
    host: !host
      <<: *login_node
    mounts:
      - *supercloud_code_mount
    runner: *supercloud-slurm
    launch:
      type: ssh
      <<: *login_node
run: *supercloud